# Generated by Django 2.1.15 on 2020-12-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=50)),
                ('ric', models.CharField(max_length=50)),
                ('weights', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('shares', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('currency', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('quote_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Portfolio Composition',
                'verbose_name_plural': 'Portfolio Composition',
                'db_table': 'portfolio_composition',
            },
        ),
        migrations.CreateModel(
            name='PortfolioDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=55)),
                ('identifier', models.CharField(max_length=55)),
                ('constituents_file_download', models.CharField(max_length=55)),
                ('file_name', models.FileField(upload_to='documents/')),
                ('spin_off_treatment', models.CharField(max_length=55)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('index_value_pr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('market_value_pr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('divisor_pr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('index_value_tr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('market_value_tr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('divisor_tr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('index_value_ntr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('market_value_ntr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('divisor_ntr', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('period', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Portfolio Description',
                'verbose_name_plural': 'Portfolio Description',
                'db_table': 'portfolio_description',
            },
        ),
        migrations.AddField(
            model_name='portfoliocomposition',
            name='portfolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.PortfolioDescription'),
        ),
    ]
