# Generated by Django 2.1.15 on 2020-12-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_taxrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='index_value_ntr',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
    ]
