# Generated by Django 2.1.15 on 2021-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_taxrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Currency Code',
                'verbose_name_plural': 'Currency Code',
                'db_table': 'currency_code',
            },
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='tax',
            field=models.CharField(max_length=50),
        ),
    ]
