# Generated by Django 2.1.15 on 2021-01-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_auto_20210107_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencycode',
            old_name='country_code',
            new_name='currency_code',
        ),
    ]
