# Generated by Django 2.1.15 on 2021-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_auto_20210107_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodescription',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='portfoliodescription',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
